{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2020-14422",
        "STATE": "PUBLIC"
    },
    "affects": {
        "vendor": {
            "vendor_data": [
                {
                    "product": {
                        "product_data": [
                            {
                                "product_name": "n/a",
                                "version": {
                                    "version_data": [
                                        {
                                            "version_value": "n/a"
                                        }
                                    ]
                                }
                            }
                        ]
                    },
                    "vendor_name": "n/a"
                }
            ]
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
        "description_data": [
            {
                "lang": "eng",
                "value": "Lib/ipaddress.py in Python through 3.8.3 improperly computes hash values in the IPv4Interface and IPv6Interface classes, which might allow a remote attacker to cause a denial of service if an application is affected by the performance of a dictionary containing IPv4Interface or IPv6Interface objects, and this attacker can cause many dictionary entries to be created."
            }
        ]
    },
    "problemtype": {
        "problemtype_data": [
            {
                "description": [
                    {
                        "lang": "eng",
                        "value": "n/a"
                    }
                ]
            }
        ]
    },
    "references": {
        "reference_data": [
            {
                "url": "https://bugs.python.org/issue41004",
                "refsource": "MISC",
                "name": "https://bugs.python.org/issue41004"
            },
            {
                "url": "https://github.com/python/cpython/pull/20956",
                "refsource": "MISC",
                "name": "https://github.com/python/cpython/pull/20956"
            },
            {
                "refsource": "SUSE",
                "name": "openSUSE-SU-2020:0931",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-07/msg00003.html"
            },
            {
                "refsource": "SUSE",
                "name": "openSUSE-SU-2020:0940",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-07/msg00006.html"
            }
        ]
    }
}